version: 2.1
jobs:
  test:
    docker:
      - image: python:slim
    steps:
      - run:
          name: install git
          command: |
            apt update && apt install -y git
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "web/requirements.txt" }}
            - dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip && pip install -r web/requirements.txt
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            pylint --disable=R,C,W1203 web/app.py 
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "web/requirements.txt" }}
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t ${DOCKER_HUB_USERNAME}/catalog-db:1.0.1 ./db
          docker build -t ${DOCKER_HUB_USERNAME}/catalog-web:1.0.1 ./web
      - run: |
          docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_PASSWORD}
          docker push ${DOCKER_HUB_USERNAME}/catalog-db:1.0.1
          docker push ${DOCKER_HUB_USERNAME}/catalog-web:1.0.1
  create_cluster:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run: |
          mkdir ~/bin
          export URL="https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
          curl --silent --location ${URL} | tar xz -C ~/bin
          ~/bin/eksctl create cluster --name ${AWS_CLUSTER_NAME} --region ${AWS_DEFAULT_REGION} \
          --with-oidc --ssh-access --ssh-public-key ${AWS_SSH_KEY}

workflows:
  eks_application:
    jobs:
      - test
      - build:
          requires: [test]
      - create_cluster:
          requires: [build]
