version: 2.1
jobs:
  test:
    docker:
      - image: python:slim
    steps:
      - run:
          name: install git
          command: |
            apt update && apt install -y git
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "web/requirements.txt" }}
            - dependencies-
      - run:
          name: install dependencies
          command: |
            ls
            pwd
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip && pip install -r web/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "web/requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            pylint --disable=R,C,W1203 web/app.py 

workflows:
  default:
    jobs:
      - test
